### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by brpaz** [greybax/generator-badges#1]
Hi. When running your generator, I got the following error:

``` javascript
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Function.all (native)
    at module.exports.yeoman.Base.extend.writing.app (/media/DATA/Projects/personal/generators/generator-badges/app/index.js:81:21)
    at Object.<anonymous> (/media/DATA/Projects/personal/generators/generator-badges/node_modules/yeoman-generator/lib/base.js:436:25)
    at /media/DATA/Projects/personal/generators/generator-badges/node_modules/run-async/index.js:26:25
    at /media/DATA/Projects/personal/generators/generator-badges/node_modules/run-async/index.js:25:19
    at /media/DATA/Projects/personal/generators/generator-badges/node_modules/yeoman-generator/lib/base.js:448:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I think the problem is that you are calling `Promise.all()` without arguments and according to [this](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) it must receive an iterable object.

If i pass an empty array like `Promise.all([])` it works.
Not sure if is the best way. Is that promise really needed?

**Comment by greybax** [comment]
thank you for logged issue! :+1: 
Removed Promise, for now it's not required
